name: Instagram Repost Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # প্রতি ৪ ঘণ্টা পর পর স্বয়ংক্রিয়ভাবে চলবে

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instaloader instabot

      - name: Run Python Script
        env:
          DOWNLOADER_INSTA_USER: ${{ secrets.DOWNLOADER_INSTA_USER }}
          DOWNLOADER_INSTA_PASS: ${{ secrets.DOWNLOADER_INSTA_PASS }}
          UPLOADER_INSTA_USER: ${{ secrets.UPLOADER_INSTA_USER }}
          UPLOADER_INSTA_PASS: ${{ secrets.UPLOADER_INSTA_PASS }}
        run: python main.py

      - name: Commit and Push Log File
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add log.csv
          git diff --quiet --exit-code log.csv || (git commit -m "Update log file" && git push)